C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3) + Metric(1,3)*Metric(2,4) -
C      2*Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV8_4(V1, V2, V3, COUP, M4, W4,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M4
      REAL*8 OM4
      REAL*8 P4(0:3)
      COMPLEX*16 TMP17
      COMPLEX*16 TMP18
      COMPLEX*16 TMP19
      COMPLEX*16 TMP2
      COMPLEX*16 TMP6
      COMPLEX*16 TMP8
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      REAL*8 W4
      COMPLEX*16 DENOM
      OM4 = 0D0
      IF (M4.NE.0D0) OM4=1D0/M4**2
      V4(1) = +V1(1)+V2(1)+V3(1)
      V4(2) = +V1(2)+V2(2)+V3(2)
      P4(0) = -DBLE(V4(1))
      P4(1) = -DBLE(V4(2))
      P4(2) = -DIMAG(V4(2))
      P4(3) = -DIMAG(V4(1))
      TMP17 = (V1(3)*P4(0)-V1(4)*P4(1)-V1(5)*P4(2)-V1(6)*P4(3))
      TMP18 = (V2(3)*P4(0)-V2(4)*P4(1)-V2(5)*P4(2)-V2(6)*P4(3))
      TMP19 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP2 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP6 = (V1(3)*V3(3)-V1(4)*V3(4)-V1(5)*V3(5)-V1(6)*V3(6))
      TMP8 = (V2(3)*V3(3)-V2(4)*V3(4)-V2(5)*V3(5)-V2(6)*V3(6))
      DENOM = COUP/(P4(0)**2-P4(1)**2-P4(2)**2-P4(3)**2 - M4 * (M4 -CI
     $ * W4))
      V4(3)= DENOM*(OM4*P4(0)*(+CI*(TMP8*TMP17+TMP6*TMP18)-2D0 * CI
     $ *(TMP2*TMP19))+(-CI*(V1(3)*TMP8+V2(3)*TMP6)+2D0 * CI*(TMP2*V3(3)
     $ )))
      V4(4)= DENOM*(OM4*P4(1)*(+CI*(TMP8*TMP17+TMP6*TMP18)-2D0 * CI
     $ *(TMP2*TMP19))+(-CI*(V1(4)*TMP8+V2(4)*TMP6)+2D0 * CI*(TMP2*V3(4)
     $ )))
      V4(5)= DENOM*(OM4*P4(2)*(+CI*(TMP8*TMP17+TMP6*TMP18)-2D0 * CI
     $ *(TMP2*TMP19))+(-CI*(V1(5)*TMP8+V2(5)*TMP6)+2D0 * CI*(TMP2*V3(5)
     $ )))
      V4(6)= DENOM*(OM4*P4(3)*(+CI*(TMP8*TMP17+TMP6*TMP18)-2D0 * CI
     $ *(TMP2*TMP19))+(-CI*(V1(6)*TMP8+V2(6)*TMP6)+2D0 * CI*(TMP2*V3(6)
     $ )))
      END


