ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_U35_MwScheme_UFO'
     $ //'-SMlimit_massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_283 = ', GC_283
      WRITE(*,2) 'GC_451 = ', GC_451
