ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_U35_MwScheme_UFO'
     $ //'-SMlimit_massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_97 = ', GC_97
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_137 = ', GC_137
      WRITE(*,2) 'GC_138 = ', GC_138
      WRITE(*,2) 'GC_260 = ', GC_260
      WRITE(*,2) 'GC_266 = ', GC_266
      WRITE(*,2) 'GC_272 = ', GC_272
      WRITE(*,2) 'GC_276 = ', GC_276
      WRITE(*,2) 'GC_283 = ', GC_283
      WRITE(*,2) 'GC_320 = ', GC_320
      WRITE(*,2) 'GC_328 = ', GC_328
      WRITE(*,2) 'GC_451 = ', GC_451
      WRITE(*,2) 'GC_219 = ', GC_219
