ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cHW = ', MDL_CHW
      WRITE(*,*) 'mdl_LambdaSMEFT = ', MDL_LAMBDASMEFT
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cHG = ', MDL_CHG
      WRITE(*,*) 'mdl_dWW = ', MDL_DWW
      WRITE(*,*) 'mdl_cHl3 = ', MDL_CHL3
      WRITE(*,*) 'mdl_dkH = ', MDL_DKH
      WRITE(*,*) 'mdl_dgw = ', MDL_DGW
      WRITE(*,*) 'mdl_dMH2 = ', MDL_DMH2
      WRITE(*,*) 'mdl_cHWB = ', MDL_CHWB
      WRITE(*,*) 'mdl_cHB = ', MDL_CHB
      WRITE(*,*) 'mdl_dGf = ', MDL_DGF
      WRITE(*,*) 'mdl_cHq3 = ', MDL_CHQ3
      WRITE(*,*) 'mdl_dWHb = ', MDL_DWHB
      WRITE(*,*) 'mdl_dWHta = ', MDL_DWHTA
      WRITE(*,*) 'mdl_dWHc = ', MDL_DWHC
      WRITE(*,*) 'mdl_dg1 = ', MDL_DG1
      WRITE(*,*) 'mdl_cH = ', MDL_CH
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_MWsm = ', MDL_MWSM
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_nb__2__exp__0_25 = ', MDL_NB__2__EXP__0_25
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_sth2 = ', MDL_STH2
      WRITE(*,*) 'mdl_nb__10__exp___m_40 = ', MDL_NB__10__EXP___M_40
      WRITE(*,*) 'mdl_MZ1 = ', MDL_MZ1
      WRITE(*,*) 'mdl_MH1 = ', MDL_MH1
      WRITE(*,*) 'mdl_MT1 = ', MDL_MT1
      WRITE(*,*) 'mdl_WZ1 = ', MDL_WZ1
      WRITE(*,*) 'mdl_WW1 = ', MDL_WW1
      WRITE(*,*) 'mdl_WH1 = ', MDL_WH1
      WRITE(*,*) 'mdl_WT1 = ', MDL_WT1
      WRITE(*,*) 'mdl_cth = ', MDL_CTH
      WRITE(*,*) 'mdl_MW1 = ', MDL_MW1
      WRITE(*,*) 'mdl_sqrt__sth2 = ', MDL_SQRT__STH2
      WRITE(*,*) 'mdl_sth = ', MDL_STH
      WRITE(*,*) 'mdl_LambdaSMEFT__exp__2 = ', MDL_LAMBDASMEFT__EXP__2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_MH__exp__6 = ', MDL_MH__EXP__6
      WRITE(*,*) 'mdl_MWsm__exp__6 = ', MDL_MWSM__EXP__6
      WRITE(*,*) 'mdl_MH__exp__4 = ', MDL_MH__EXP__4
      WRITE(*,*) 'mdl_MWsm__exp__4 = ', MDL_MWSM__EXP__4
      WRITE(*,*) 'mdl_MWsm__exp__2 = ', MDL_MWSM__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_MZ__exp__6 = ', MDL_MZ__EXP__6
      WRITE(*,*) 'mdl_cth__exp__2 = ', MDL_CTH__EXP__2
      WRITE(*,*) 'mdl_sth__exp__2 = ', MDL_STH__EXP__2
      WRITE(*,*) 'mdl_MB__exp__2 = ', MDL_MB__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__3 = ', MDL_MZ__EXP__3
      WRITE(*,*) 'mdl_sth__exp__4 = ', MDL_STH__EXP__4
      WRITE(*,*) 'mdl_sth__exp__6 = ', MDL_STH__EXP__6
      WRITE(*,*) 'mdl_sth__exp__3 = ', MDL_STH__EXP__3
      WRITE(*,*) 'mdl_sth__exp__5 = ', MDL_STH__EXP__5
      WRITE(*,*) 'mdl_cth__exp__3 = ', MDL_CTH__EXP__3
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_sqrt__Gf = ', MDL_SQRT__GF
      WRITE(*,*) 'mdl_vevhat = ', MDL_VEVHAT
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_vevhat__exp__2 = ', MDL_VEVHAT__EXP__2
      WRITE(*,*) 'mdl_vevT = ', MDL_VEVT
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_gHaa = ', MDL_GHAA
      WRITE(*,*) 'mdl_gHza = ', MDL_GHZA
      WRITE(*,*) 'mdl_barlam = ', MDL_BARLAM
      WRITE(*,*) 'mdl_gwsh = ', MDL_GWSH
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_g1sh = ', MDL_G1SH
      WRITE(*,*) 'mdl_ee__exp__3 = ', MDL_EE__EXP__3
      WRITE(*,*) 'mdl_vevhat__exp__3 = ', MDL_VEVHAT__EXP__3
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_gHgg2 = ', MDL_GHGG2
      WRITE(*,*) 'mdl_gHgg4 = ', MDL_GHGG4
      WRITE(*,*) 'mdl_gHgg5 = ', MDL_GHGG5
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_gHgg1 = ', MDL_GHGG1
      WRITE(*,*) 'mdl_gHgg3 = ', MDL_GHGG3
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_dWH = ', MDL_DWH
